name: Implantar na VPS

on:
  push:
    branches:
      - master

jobs:
  implantar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }} # Usando a senha em vez da chave
          port: 22
          script: |
            cd /root/analisador
            git pull
            source .venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart analisador
